---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse-role

- name: Install Vector
  hosts: vector
  roles:
    - role: vector-role

- name: Install Lighthouse
  hosts: lighthouse

  handlers:
    - name: Start nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Update Repository
      become: true
      ansible.builtin.apt:
        update_cache: true
    - name: Install Nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: Start nginx service
    - name: Create Nginx config
      become: true
      ansible.builtin.template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Start nginx service

  roles:
    - role: lighthouse-role

  # post_tasks:
  #   - name: Show connect URL lighthouse
  #     ansible.builtin.debug:
  #       msg: "http://{{ ansible_host }}/#http://{{ hostvars['clickhouse-01'].ansible_host }}:8123/?user={{ clickhouse_user }}"
